### ISSUE TITLE
binder connection can fail

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/thebe#625]
### Describe the bug

**context**
When a binder connection is made, close to the end of the handshake the following error occurs

![image](https://user-images.githubusercontent.com/1473646/236451343-f98d2b23-447d-4db4-96a1-1eca499eb16c.png)

**expectation**
I expected the binder connection to complete and a server session to become available

**bug**
But instead is just fails

### Reproduce the bug

using the following config from `myst-theme`
```
  thebe:
    binder:
      binderUrl: https://xhrtcvh6l53u.curvenote.dev/services/binder
      repo: stevejpurves/seg_tutorial
      ref: main
```
