### ISSUE TITLE
Server port is not used

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/thebe#675]
When using the "server" configuration in MyST the port is not respected, and the default is used instead (i.e. 8888).

```
thebe:
  server:
    ...
    port: 8889
```
