### ISSUE TITLE
Missing global variable in the `Window` interface

### ISSUE THREAD

**Issue by ManonMarchand** [executablebooks/thebe#679]
### Describe the bug

Hi thebe devs and thanks for your software!

## Context

We (@bmatthieu3 and I) 're trying to output a jupyter widget ([ipyaladin](https://github.com/cds-astro/ipyaladin)) with thebe-lite. 

This widget is written in JS and exports a variable `A` to `window`. It works in jupyterlite. See https://cds-astro.github.io/jupyterlite/retro/notebooks/index.html?path=01-intro-to-python-vizier-and-ipyaladin.ipynb 

## The issue

But with thebe-lite, the widget cannot export A in window and we don't get why. See a live example here : 

https://manonmarchand.github.io/draft-thebe-jupyterlite-app/aladin-test

where we get the following issue in the console : 

```
Uncaught (in promise) ReferenceError: A is not defined
```

And indeed A is not there.
A second run of the cell trying to output the widget gets a different error : 

```
Error: Mismatched anonymous define() module: function(){"use strict";var Zg=typeof globalThis<"u"?globalThis:typeof window<"u"?window:typeof global<"u"?global:typeof self<"u"?self:{};function Tg(B){return B&&B.__esModule&&Object.prototype.hasOwnProperty.call(B,"default")?B.default:B}var NB={exports:{}};/*!
 * jQuery JavaScript Library v3.6.1
 * https://jquery.com/
```

​Do you know what's happening? 

Thanks a lot, and we hope this is the right place to ask the question. 

### Reproduce the bug

https://manonmarchand.github.io/draft-thebe-jupyterlite-app/aladin-test

### List your environment

The page is generated with the following steps : 

```yml
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install MyST Markdown
        run: npm install -g mystmd
      - name: Build HTML Assets
        run: myst build --html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

that can be found in this repo: https://github.com/ManonMarchand/draft-thebe-jupyterlite-app
